CREATE TABLE PRODUCT (
	WAREHOUSE VARCHAR(15),
	BAR_CODE VARCHAR(30),
	DESIGNATION VARCHAR(200),
	CATEGORY VARCHAR(100),
	SUB_CATEGORY VARCHAR(100),
	PRICE DECIMAL(18, 4),
	STOCK int,
	REFS VARCHAR(2000)
);

CREATE INDEX ix_barcode ON PRODUCT (
	BAR_CODE
);

--CREATE TABLE REPLICATION_CONTROL ();

CREATE TABLE REPLICATION_LOG (
	ID varchar(50) PRIMARY KEY,
	START_DATE TIMESTAMP,
	END_DATE TIMESTAMP,
	STATUS varchar(10),
	ELAPSED_MS BIGINT,
	RESULT varchar(2000)
	
);

CREATE INDEX ix_repl_id ON REPLICATION_LOG (
	ID
);

SELECT ELAPSED_MS, END_DATE, result, START_DATE
FROM REPLICATION_LOG;